Roads/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Roads.Models
{
    public class Event
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string City { get; set; }

        //[Required]
        //public string State { get; set; }

        [Required]
        public string Address { get; set; }

        [Display(Name = "Secondary Address (optional)")]
        public string SecondaryAddress { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }

        [Required]
        public int EventTypeId { get; set; }

        [Display(Name = "Event Type")]
        public EventType EventType { get; set; }

        [Required]
        public string ApplicationUserId { get; set; }

        [Display(Name = "Hosted By")]
        public ApplicationUser ApplicationUser { get; set; }
    }
}

Roads/Models/EventType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Roads.Models
{
    public class EventType
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

Roads/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Roads.Data;
using Roads.Models;
using Roads.Models.ViewModels;

namespace Roads.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public EventsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)

        {

            _context = context;
            _userManager = userManager;

        }


        // GET: Events
        public async Task<ActionResult> Index(string searchString, string filter)
        {
            var user = await GetCurrentUserAsync();
            var events = await _context.Event
                //.Where(ti => ti.ApplicationUserId == user.Id)
                .Include(tdi => tdi.ApplicationUser)
                .Include(tdi => tdi.EventType)
                .ToListAsync();

            switch (filter)
            {
                case "General Car Show":
                    events = await _context.Event
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.EventTypeId == 1)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
                case "Classic & Hot Rod Show":
                    events = await _context.Event
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.EventTypeId == 4)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
                case "Stance Car Show":
                    events = await _context.Event
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.EventTypeId == 5)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
                case "Racing Festival":
                    events = await _context.Event
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.EventTypeId == 6)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
                case "Brand Specific":
                    events = await _context.Event
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.EventTypeId == 7)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
                case "Cruise & Drive":
                    events = await _context.Event
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.EventTypeId == 1004)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
                case "Rally":
                    events = await _context.Event
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.EventTypeId == 1005)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
                case "Racing/Drifting Events":
                    events = await _context.Event
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.EventTypeId == 1006)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
                case "All":
                    events = await _context.Event
                        //.Where(ti => ti.UserId == user.Id)
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
                default:
                    events = await _context.Event
                        .Include(ti => ti.EventType)
                        .ToListAsync();
                    break;
            }

            if (searchString != null)
            {
                var filteredEvents = _context.Event.Where(s => s.Name.Contains(searchString) || s.City.Contains(searchString));
                return View(filteredEvents);
            };

            return View(events);
        }



        // GET: Events/Details/1
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventt = await _context.Event
               //.Where(p => p.UserId == user.Id)
               .Include(p => p.ApplicationUser)
               .Include(p => p.EventType)
               .FirstOrDefaultAsync(p => p.Id == id);

            if (eventt == null)
            {
                return NotFound();
            }

            return View(eventt);
        }



        // GET: Events/Create
        public async Task<ActionResult> Create()
        {
            var eventTypeOptions = await _context.EventType.Select(e => new SelectListItem()
            {
                Text = e.Name,
                Value = e.Id.ToString()
            })
                .ToListAsync();
            var viewModel = new EventFormViewModel();
            viewModel.EventTypeOptions = eventTypeOptions;
            return View(viewModel);
        }


        // POST: Events/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EventFormViewModel eventFormView)
        {
            try
            {
                var user = await GetCurrentUserAsync();
                var events = new Event()
                {
                    Name = eventFormView.Name,
                    City = eventFormView.City,
                    Address = eventFormView.Address,
                    SecondaryAddress = eventFormView.SecondaryAddress,
                    Description = eventFormView.Description,
                    ImagePath = eventFormView.ImagePath,
                    ApplicationUserId = user.Id,
                    EventTypeId = eventFormView.EventTypeId,
                };


                _context.Event.Add(events);
                await _context.SaveChangesAsync();

                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: Events/Edit/1
        public async Task<ActionResult> Edit(int id)
        {
            var loggedInUser = await GetCurrentUserAsync();
            var eventTypes = await _context.EventType.Select(e => new SelectListItem()
            {
                Text = e.Name,
                Value = e.Id.ToString()
            })
               .ToListAsync();

            var eventt = await _context.Event.FirstOrDefaultAsync(e => e.Id == id);
            var viewModel = new EventFormViewModel()
            {
                Name = eventt.Name,
                City = eventt.City,
                Address = eventt.Address,
                SecondaryAddress = eventt.SecondaryAddress,
                ImagePath = eventt.ImagePath,
                EventTypeId = eventt.EventTypeId,
                EventTypeOptions = eventTypes,
            };

            if (eventt.ApplicationUserId != loggedInUser.Id)
            {
                return NotFound();
            }

            return View(viewModel);
        }


        // POST: Parts/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, EventFormViewModel eventFormView)
        {
            try
            {
                var user = await GetCurrentUserAsync();
                var events = new Event()
                {
                    Id = id,
                    Name = eventFormView.Name,
                    City = eventFormView.City,
                    Address = eventFormView.Address,
                    SecondaryAddress = eventFormView.SecondaryAddress,
                    ImagePath = eventFormView.ImagePath,
                    ApplicationUserId = user.Id,
                    EventTypeId = eventFormView.EventTypeId,
                };

                _context.Event.Update(events);
                await _context.SaveChangesAsync();
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: Events/Delete/1
        public async Task<ActionResult> Delete(int id)
        {
            var loggedInUser = await GetCurrentUserAsync();

            var eventt = await _context.Event
                .Include(e => e.ApplicationUser)
                .FirstOrDefaultAsync(e => e.Id == id);

            if (eventt.ApplicationUserId != loggedInUser.Id)
            {
                return NotFound();
            }

            return View(eventt);
        }


        // POST: Events/Delete/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {

Roads/Views/Events/Create.cshtml
@model Roads.Models.ViewModels.EventFormViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAddress" class="control-label"></label>
                <input asp-for="SecondaryAddress" class="form-control" />
                <span asp-validation-for="SecondaryAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventType" class="control-label"></label>
                <select asp-for="EventTypeId" class="form-control" asp-items="@Model.EventTypeOptions">
                    <option selected value="null" disabled> Please select a type</option>
                </select>
                <span asp-validation-for="EventTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Roads/Views/Events/Delete.cshtml
@model Roads.Models.Event

@{
    ViewData["Title"] = "Delete";
}


<div id="deets">
    <image class="DeetTitle" src="@Html.DisplayFor(model => model.ImagePath)" alt="Product Image Unavailable" width="520" height="450" />
    <h3 class="DeetTitle">Are you sure you want to delete @Html.DisplayFor(model => model.Name) in @Html.DisplayFor(model => model.City)?</h3>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Roads/Views/Events/Details.cshtml
@model Roads.Models.Event

@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Details";
}

@{
    var currentUser = await UserManager.GetUserAsync(User);
}




<div>
    <dl id="deets" class="row">
        <div>
            <image src="@Html.DisplayFor(model => model.ImagePath)" alt="Product Image Unavailable" width="520" height="450" />
            <h3 class="DeetTitle">@Html.DisplayFor(model => model.Name)</h3>
            <div class="DeetTitle">
                @Html.DisplayFor(model => model.EventType.Name)
            </div>
            <div class="DeetTitle">
                @Html.DisplayFor(model => model.Address)
                <br />
                @Html.DisplayFor(model => model.City)
            </div>
            @if (Model.SecondaryAddress != null)
            {
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.SecondaryAddress)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.SecondaryAddress)
                    <br />
                    @Html.DisplayFor(model => model.City)
                </dd>
            }
            else
            {
            }
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ApplicationUser)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ApplicationUser.FirstName)
            </dd>
        </div>
    </dl>
</div>
<div>
    @if (Model.ApplicationUserId != currentUser.Id)
    {
    }
    else
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
    }
    <br />
    <a asp-action="Index">Back to List</a>
</div>

Roads/Views/Events/Edit.cshtml
@model Roads.Models.ViewModels.EventFormViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="SecondaryAddress" class="control-label"></label>
                <input asp-for="SecondaryAddress" class="form-control" value="N/A"/>
                <span asp-validation-for="SecondaryAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventType" class="control-label"></label>
                <select asp-for="EventTypeId" class="form-control" asp-items="@Model.EventTypeOptions">
                    <option selected value="null" disabled> Please select a type</option>
                </select>
                <span asp-validation-for="EventTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Roads/Views/Events/Index.cshtml
@model IEnumerable<Roads.Models.Event>

@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Index";
}

@{
    var currentUser = await UserManager.GetUserAsync(User);
}


    <div class="EBan">
        <h1 class="display-4" id="eBanText">Events</h1>
        @*<p id="eBanText">Here are some events</p>*@
    </div>
    <br />
    <form asp-controller="Events" asp-action="Index">
        <div>
            <input type="text" name="SearchString" placeholder=" Search by Name or City...">
            <input type="submit" value="Search" />
        </div>
    </form>
    <br />
    <p>
        <a type="submit" asp-action="Create">Create New</a>
    </p>
    <br />
    <div>
        <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="General Car Show">General Car Shows</a>
        <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Classic & Hot Rod Show">Classic & Hot Rod</a>
        <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Stance Car Show">Stance</a>
        <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Brand Specific">Brand Specific</a>
        <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Racing Festival">Racing Festivals</a>
        <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Racing/Drifting Events">Racing/Drifting Events</a>
        <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Rally">Rallies</a>
        <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Cruise & Drive">Cruise & Drive</a>
        <a type="button" class="btn btn-info mb-2" asp-action="Index" asp-route-filter="All">Show All</a>
    </div>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.ImagePath)*@
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.Address)*@
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.Name)*@
                </th>
                
                <th>
                    @*@Html.DisplayNameFor(model => model.EventType)*@
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody class="TIndex">
            @foreach (var item in Model)
            {
            <tr class="TContainer">
                <td>
                    <image src="@Html.DisplayFor(modelItem => item.ImagePath)" alt="Product Image Unavailable" width="350" height="250" />
                </td>
                <td>          </td>
                <td class="TPart">
                    <h2>@Html.DisplayFor(modelItem => item.Name)</h2>
                </td>
                <td class="TPart">
                    @Html.DisplayFor(modelItem => item.EventType.Name)
                </td>
                <td class="TPart">
                    <div class="Addy">
                        <div>@Html.DisplayFor(modelItem => item.Address)</div>
                        <div>@Html.DisplayFor(modelItem => item.City)@*, @Html.DisplayFor(modelItem => item.State)*@</div>
                    </div>
                </td>
                
                <td class="TButt">
                    @if (item.ApplicationUserId != currentUser.Id)
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.Id })
                    }
                    else
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.Id })
                        <br />
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                        <br />
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    }
                </td>
                <td>          </td>
            </tr>
            }
        </tbody>
    </table>