Roads/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Roads.Models
{
    public class Car
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Make { get; set; }
        [Required]
        public string Model { get; set; }
        [Required]
        public int Year { get; set; }

        [Required]
        [Display(Name = "Original Color")]
        public string Color { get; set; }

        [Display(Name = "Image Url")]
        public string ImagePath { get; set; }

        [Display(Name = "Performance")]
        public string PerformanceMods { get; set; }

        [Display(Name = "Aesthetic")]
        public string AstheticMods { get; set; }
        [Required]
        public string ApplicationUserId { get; set; }
        [Display(Name = "By")]
        public ApplicationUser ApplicationUser { get; set; }
    }
}

Roads/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Roads.Data;
using Roads.Models;

namespace Roads.Controllers
{
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CarsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)

        {

            _context = context;
            _userManager = userManager;

        }


        // GET: Cars
        public async Task<ActionResult> Index(string searchString)
        {
            var user = await GetCurrentUserAsync();
            var cars = await _context.Car
                //.Where(ti => ti.ApplicationUserId == user.Id)
                .Include(tdi => tdi.ApplicationUser)
                .ToListAsync();

            if (searchString != null)
            {
                var filteredCars = _context.Car.Where(s => s.Make.Contains(searchString) || s.Model.Contains(searchString));
                return View(filteredCars);
            };

            return View(cars);
        }


        // GET: Cars/Details/1
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
               //.Where(p => p.UserId == user.Id)
               .Include(p => p.ApplicationUser)
               .FirstOrDefaultAsync(p => p.Id == id);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }



        // GET: Cars/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: Cars/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Car car)
        {
            try
            {
                var user = await GetCurrentUserAsync();
                car.ApplicationUserId = user.Id;

                _context.Car.Add(car);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: Cars/Edit/1
        public async Task<ActionResult> Edit(int id)
        {
            var car = await _context.Car.FirstOrDefaultAsync(p => p.Id == id);
            var loggedInUser = await GetCurrentUserAsync();

            if (car.ApplicationUserId != loggedInUser.Id)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Paintings/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Car car)
        {
            try
            {
                var user = await GetCurrentUserAsync();
                car.ApplicationUserId = user.Id;

                _context.Car.Update(car);
                await _context.SaveChangesAsync();
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: Cars/Delete/1
        public async Task<ActionResult> Delete(int id)
        {
            var loggedInUser = await GetCurrentUserAsync();
            var car = await _context.Car
                .Include(p => p.ApplicationUser)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (car == null)
            {
                return NotFound();
            }

            if (car.ApplicationUserId != loggedInUser.Id)
            {
                return NotFound();
            }

            return View(car);
        }


        // POST: Cars/Delete/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                var car = await _context.Car.FindAsync(id);
                _context.Car.Remove(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

    }
}

Roads/Views/Cars/Create.cshtml
@model Roads.Models.Car

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Make" class="control-label"></label>
                <input asp-for="Make" class="form-control" />
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PerformanceMods" class="control-label"></label>
                <input asp-for="PerformanceMods" class="form-control" />
                <span asp-validation-for="PerformanceMods" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AstheticMods" class="control-label"></label>
                <input asp-for="AstheticMods" class="form-control" />
                <span asp-validation-for="AstheticMods" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Roads/Views/Cars/Delete.cshtml
@model Roads.Models.Car

@{
    ViewData["Title"] = "Delete";
}


<div id="deets">
    <image class="DeetTitle" src="@Html.DisplayFor(model => model.ImagePath)" alt="Product Image Unavailable" width="520" height="450" />
    <h3 class="DeetTitle">Are you sure you want to delete @Html.DisplayFor(model => model.Year) @Html.DisplayFor(model => model.Make) @Html.DisplayFor(model => model.Make)?</h3>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Roads/Views/Cars/Details.cshtml
@model Roads.Models.Car

@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Details";
}

@{
    var currentUser = await UserManager.GetUserAsync(User);
}



<div>
    <dl id="deets" class="row">
        <image src="@Html.DisplayFor(model => model.ImagePath)" alt="Product Image Unavailable" width="545" height="440" />
        <h3 class="DeetTitle">@Html.DisplayFor(model => model.Make) @Html.DisplayFor(model => model.Model) @Html.DisplayFor(model => model.Year) </h3>
        <div>
            <dt class="col-sm-2">
                <h5>Modifications</h5>
            </dt>
            <dd class="col-sm-10">
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PerformanceMods)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PerformanceMods)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AstheticMods)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AstheticMods)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Color)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Color)
            </dd>
            <dt class="col-sm-2">
                By.
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ApplicationUser.FirstName)
            </dd>
        </div>
    </dl>
</div>
<div>
    @if (Model.ApplicationUserId != currentUser.Id)
    {
    }
    else
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
    }
    <br />
    <a asp-action="Index">Back to List</a>
</div>

Roads/Views/Cars/Edit.cshtml
@model Roads.Models.Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger">
            </div>
            <div class="form-group">
                <label asp-for="Make" class="control-label"></label>
                <input asp-for="Make" class="form-control" />
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PerformanceMods" class="control-label"></label>
                <input asp-for="PerformanceMods" class="form-control" />
                <span asp-validation-for="PerformanceMods" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AstheticMods" class="control-label"></label>
                <input asp-for="AstheticMods" class="form-control" />
                <span asp-validation-for="AstheticMods" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Roads/Views/Cars/Index.cshtml
@model IEnumerable<Roads.Models.Car>

@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Index";
}

@{
    var currentUser = await UserManager.GetUserAsync(User);
}

<div class="CBan">
    <h1 class="display-4" id="cBanText">Car Builds</h1>
    @*<p id="pBanText">Here are some parts</p>*@
</div>
<br />
<form asp-controller="Cars" asp-action="Index">
    <div>
        <input type="text" name="SearchString" placeholder=" Search by Make or Model...">
        <input type="submit" value="Search" />
    </div>
</form>
<br />
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.ImagePath)*@
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Make)*@ @*@Html.DisplayNameFor(model => model.Model)*@
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Year)*@
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.ApplicationUser)*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="TIndex">
        @foreach (var item in Model)
        {
        <tr class="TContainer">
            <td>
                <image src="@Html.DisplayFor(modelItem => item.ImagePath)" alt="Product Image Unavailable" width="340" max-height="250" />
            </td>
            <td>           </td>
            <td class="TPart">
                <h3>@Html.DisplayFor(modelItem => item.Make) @Html.DisplayFor(modelItem => item.Model)</h3>
            </td>
            <td class="TPart">
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td class="TPart">
                by. @Html.DisplayFor(modelItem => item.ApplicationUser.FirstName)
            </td>
            <td class="TButt">
                @if (item.ApplicationUserId != currentUser.Id)
                {
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                }
                else
                {
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                    <br />
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    <br />
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                }
            </td>
            <td>          </td>
        </tr>
        }
    </tbody>
</table>