Roads/Models/Part.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Roads.Models
{
    public class Part
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public string Brand { get; set; }
        public string ImagePath { get; set; }

        [Required]
        public int PartTypeId { get; set; }
        [Display(Name = "Part Type")]
        public PartType PartType { get; set; }

        [Required]
        public string ApplicationUserId { get; set; }

        [Display(Name = "Posted By")]
        public ApplicationUser ApplicationUser { get; set; }
    }
}

Roads/Models/PartType.cs
    using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Roads.Models
{
    public class PartType
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

Roads/Controllers/PartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Roads.Data;
using Roads.Models;
using Roads.Models.ViewModels;

namespace Roads.Controllers
{
    public class PartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PartsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)

        {

            _context = context;
            _userManager = userManager;

        }


        // GET: Parts
        public async Task<ActionResult> Index(string searchString, string filter)
        {
            var user = await GetCurrentUserAsync();
            var parts = await _context.Part
                //.Where(ti => ti.ApplicationUserId == user.Id)
                .Include(tdi => tdi.ApplicationUser)
                .Include(tdi => tdi.PartType)
                .ToListAsync();

            switch (filter)
            {
                case "Tire & Rims":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.PartTypeId == 1)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                case "Engine & Exhaust":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.PartTypeId == 2)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                case "Turbos & Superchargers":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.PartTypeId == 3)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                case "Brakes, Suspension, & Chasis":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.PartTypeId == 5)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                case "Fuel System":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.PartTypeId == 6)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                case "Coolant & Air System":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.PartTypeId == 7)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                case "Transmission":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.PartTypeId == 9)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                case "Body Parts":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.PartTypeId == 10)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                case "Other":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Where(ti => ti.PartTypeId == 11)
                        //.Where(p => p.Quantity > 0)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                case "All":
                    parts = await _context.Part
                        //.Where(ti => ti.UserId == user.Id)
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
                default:
                    parts = await _context.Part
                        .Include(ti => ti.PartType)
                        .ToListAsync();
                    break;
            }

            if (searchString != null)
            {
                var filteredParts = _context.Part.Where(s => s.Name.Contains(searchString) || s.Brand.Contains(searchString));
                return View(filteredParts);
            };

            return View(parts);
        }



        // GET: Parts/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partt = await _context.Part
               //.Where(p => p.UserId == user.Id)
               .Include(p => p.ApplicationUser)
               .Include(p => p.PartType)
               .FirstOrDefaultAsync(p => p.Id == id);

            if (partt == null)
            {
                return NotFound();
            }

            return View(partt);
        }



        // GET: Parts/Create
        public async Task<ActionResult> Create()
        {
            var partTypeOptions = await _context.PartType.Select(p => new SelectListItem() 
            { 
                Text = p.Name,
                Value = p.Id.ToString() 
            })
                .ToListAsync();
            var viewModel = new PartFormViewModel();
            viewModel.PartTypeOptions = partTypeOptions;
            return View(viewModel);
        }


        // POST: Parts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PartFormViewModel partFormView)
        {
            try
            {
                var user = await GetCurrentUserAsync();
                var parts = new Part()
                {
                    Name = partFormView.Name,
                    Brand = partFormView.Brand,
                    ImagePath = partFormView.ImagePath,
                    ApplicationUserId = user.Id,
                    PartTypeId = partFormView.PartTypeId,
                };

                
                _context.Part.Add(parts);
                await _context.SaveChangesAsync();

                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: Parts/Edit/1
        public async Task<ActionResult> Edit(int id)
        {
            var loggedInUser = await GetCurrentUserAsync();
            var partTypes = await _context.PartType.Select(p => new SelectListItem() 
            { 
                Text = p.Name, 
                Value = p.Id.ToString() 
            })
               .ToListAsync();

            var part = await _context.Part.FirstOrDefaultAsync(p => p.Id == id);
            var viewModel = new PartFormViewModel()
            {
                Name = part.Name,
                Brand = part.Brand,
                ImagePath = part.ImagePath,
                PartTypeId = part.PartTypeId,
                PartTypeOptions = partTypes,
            };

            if (part.ApplicationUserId != loggedInUser.Id)
            {
                return NotFound();
            }

            return View(viewModel);
        }


        // POST: Parts/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, PartFormViewModel partFormView)
        {
            try
            {
                var user = await GetCurrentUserAsync();
                var parts = new Part()
                {
                    Id = id,
                    Name = partFormView.Name,
                    Brand = partFormView.Brand,
                    ImagePath = partFormView.ImagePath,
                    ApplicationUserId = user.Id,
                    PartTypeId = partFormView.PartTypeId,
                };               

                _context.Part.Update(parts);
                await _context.SaveChangesAsync();
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: Parts/Delete/1
        public async Task<ActionResult> Delete(int id)
        {
            var loggedInUser = await GetCurrentUserAsync();
            var partt = await _context.Part
                .Include(p => p.ApplicationUser)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (partt.ApplicationUserId != loggedInUser.Id)
            {
                return NotFound();
            }

            return View(partt);
        }


        // POST: Parts/Delete/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                //TODO: Add delete logic here
                var partt = await _context.Part.FindAsync(id);

Roads/Views/Parts/Create.cshtml
@model Roads.Models.ViewModels.PartFormViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Part</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>          
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartType" class="control-label"></label>
                <select asp-for="PartTypeId" class="form-control" asp-items="@Model.PartTypeOptions">
                    <option selected value="null" disabled> Please select a type</option>
                </select>
                <span asp-validation-for="PartTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Roads/Views/Parts/Delete.cshtml
@model Roads.Models.Part

@{
    ViewData["Title"] = "Delete";
}


<div id="deets">
    <image class="DeetTitle" src="@Html.DisplayFor(model => model.ImagePath)" alt="Product Image Unavailable" width="520" height="450" />
    <h3 class="DeetTitle">Are you sure you want to remove this listing?
        <br/>
        @Html.DisplayFor(model => model.Name) by @Html.DisplayFor(model => model.Brand)
    </h3>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Roads/Views/Parts/Details.cshtml
@model Roads.Models.Part

@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Details";
}

@{
    var currentUser = await UserManager.GetUserAsync(User);
}


<div>
    <dl id="deets" class="row">
        <div>
            <image src="@Html.DisplayFor(model => model.ImagePath)" alt="Product Image Unavailable" width="500" height="500" />
            <br/>
            <h3 class="DeetTitle">@Html.DisplayFor(model => model.Brand) - @Html.DisplayFor(model => model.Name)</h3>
            <div class="DeetTitle">
                @Html.DisplayFor(model => model.PartType.Name)
            </div>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ApplicationUser)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ApplicationUser.FirstName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ApplicationUser.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ApplicationUser.Email)
            </dd>
        </div>
    </dl>
</div>
<div>
    @if (Model.ApplicationUserId != currentUser.Id)
    {
    }
    else
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
    }
    <br />
    <a asp-action="Index">Back to List</a>
</div>

Roads/Views/Parts/Edit.cshtml
@model Roads.Models.ViewModels.PartFormViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Part</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartType" class="control-label"></label>
                <select asp-for="PartTypeId" class="form-control" asp-items="@Model.PartTypeOptions">
                    <option selected value="null" disabled> Please select a type</option>
                </select>
                <span asp-validation-for="PartTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Roads/Views/Parts/Index.cshtml
@model IEnumerable<Roads.Models.Part>

@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Index";
}

@{
    var currentUser = await UserManager.GetUserAsync(User);
}


<div class="PBan">
    <h1 class="display-4" id="pBanText">Parts</h1>
    @*<p id="pBanText">Here are some parts</p>*@
</div>
<br />
<form asp-controller="Parts" asp-action="Index">
    <div>
        <input type="text" name="SearchString" placeholder=" Search by Name or Brand...">
        <input type="submit" value="Search" />
    </div>
</form>
<br />
<p>
    <a asp-action="Create">Create New</a>
</p>
<br />
<div>
    <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Tire & Rims">Tire & Rims</a>
    <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Engine & Exhaust">Engine & Exhaust</a>
    <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Turbos & Superchargers">Turbos & Superchargers</a>
    <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Transmission">Transmission</a>
    <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Brakes, Suspension, & Chasis">Brakes, Suspension, & Chasis</a>
    <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Fuel System">Fueling System</a>
    <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Coolant & Air System">Coolant & Air System</a>
    <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Body Parts">Body Parts</a>
    <a type="button" class="btn btn-success mb-2" asp-action="Index" asp-route-filter="Other">Other</a>
    <a type="button" class="btn btn-info mb-2" asp-action="Index" asp-route-filter="All">Show All</a>
</div>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.ImagePath)*@
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Name)*@
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.PartType)*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="TIndex">
        @foreach (var item in Model)
        {
        <tr class="TContainer">
            <td>
                <image src="@Html.DisplayFor(modelItem => item.ImagePath)" alt="Product Image Unavailable" width="220" height="150" />
            </td>
            <td>   </td>
            <td class="TPart">
                <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
            </td>
            <td class="TPart">
                @Html.DisplayFor(modelItem => item.PartType.Name)
            </td>
            <td class="TButt">
                @if (item.ApplicationUserId != currentUser.Id)
                {
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                }
                else
                {
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                    <br />
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    <br />
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                }
            </td>
            <td>   </td>
        </tr>
        }
    </tbody>
</table>